version: '3.7'

services:
  db:
    image: postgres:9.4
    container_name: database
    tty: true
    restart: always
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
